services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=yoga_app
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql:postgres:secret@postgres:5432/yoga_app
    depends_on:
      - postgres

#    entrypoint: ["postgres:5432"]

    command: ["/app/build"]

